<form  method="POST" class="needs-validation main" novalidate id="g-form">
    <nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
        <div class="navbar-multiline mr-auto">
            <span class="navbar-brand" href="#0">Gallery Editor</span>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                    <li class="breadcrumb-item"><a href="<?= $this->router->to('adminGallery') ?>">Gallery</a></li>
                    <li class="breadcrumb-item active" aria-current="page"><?= $subtitle ?></li>
                </ol>
            </nav>
        </div>
        <button class="btn btn-primary">Save</button>
    </nav>

    <div class="container p-3">
        <div class="row mb-3">
            <?= $form->csrfField('noob') ?>
            <div class="col-md-9">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <ul class="nav nav-tabs" id="editor" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="gallery-tab" data-toggle="tab" href="#gallery-form" role="tab" aria-controls="gallery-form" aria-selected="true">Gallery</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="images-tab" data-toggle="tab" href="#images-form" role="tab" aria-controls="images-form" aria-selected="false">Images</a>
                                    </li>
                                </ul>
                                <div class="tab-content">
                                    <div class="tab-pane active pt-3" id="gallery-form" role="tabpanel" aria-labelledby="gallery-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <?= $form->field('title'); ?>
                                            </div>
                                            <div class="col-md-6">
                                                <?= $form->field('slug'); ?>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <?= $form->field('content'); ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="images-form" role="tabpanel" aria-labelledby="images-tab">
                                        <?= $form->field('images'); ?>
                                        <div class="row" id="g-list"></div>
                                        <div>
                                            <button class="btn btn-secondary btn-block g-list-item-add" type="button">
                                                Add Image
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <?= $this->partial('site-meta/meta'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<?php
    \AdminUi\Library\Assets::addAsset('js', 'foot', 'js/gallery.js', '1');
?>

<style>
    .g-list-thumb{
        border: 1px solid #CCC;
        width: 66px;
        height: 66px;
        background-position: center center;
        background-size: cover;
        background-color: #eee;
    }
</style>